<?php
/*
 * OPTIONS PAGE FOR SIMPLE FACEBOOK SHARE BUTTON
 */

/*
 * Register plugin settings
 * @uses register_setting
 * @action admin_init
 * @return null
 */
function SFBSB_admin_init() {
	register_setting( 'SFBSB', 'SFBSB', 'SFBSB_validation' );
}
add_action( 'admin_init', 'SFBSB_admin_init' );

/*
 * Add menu item
 * @uses add_options_page, add_contextual_help
 * @action admin_menu
 * @return null
 */
function SFBSB_menu() {
	$page = add_options_page( 'Simple Facebook Share Button', 'Simple FB Share Button', 'administrator', 'simple_fb_share_button_options', 'SFBSB_options' );
	add_contextual_help( $page, SFBSB_help() );
}
add_action( 'admin_menu', 'SFBSB_menu' );

/*
 * Render contextual help
 * @uses admin_url
 * @return html help text
 */
function SFBSB_help() {
	$help .= '<h5>Simple Facebook Share Button Help</h5><div class="metabox-prefs">';
	$help .= '<a href="' . admin_url( 'options-general.php?page=simple_fb_share_button_options&sub=help' ) . '">Plugin Help</a><br />';
	$help .= '<a href="http://www.ethitter.com/plugins/simple-fb-share-button/" target="_blank">Plugin Homepage</a><br />';
	$help .= '<a href="http://wordpress.org/extend/plugins/simple-facebook-share-button/" target="_blank">Simple Facebook Share Button at WordPress Plugins repository</a>';
	$help .= '</div>';
	
	return $help;
}

/*
 * Render options page
 * @uses get_option, WP_PLUGIN_URL, admin_url, checked, selected, settings_fields
 */
function SFBSB_options() {
	$options = get_option( 'SFBSB' );
	$imgbase = WP_PLUGIN_URL . '/' . basename( dirname( __FILE__ ) ) . '/';
?>
	<div style="float:right; padding-left:5px; padding-bottom:5px;" align="right">
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
			<input type="hidden" name="cmd" value="_s-xclick">
			<input type="hidden" name="hosted_button_id" value="10236880">
			<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
			<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
			<br /><small>Donate to support plugin development.</small>
		</form>
	</div>
	<div class="wrap">
		<h2>Simple Facebook&reg; Share Button by <a href="http://www.ethitter.com/plugins/" target="_blank" style="text-decoration:none;">Erick Hitter</a>
	</h2>
	
	<?php if( isset( $_GET[ 'sub' ] ) && $_GET[ 'sub' ] == 'help' ): ?>
		<h4><a href="<?php echo admin_url( 'options-general.php?page=simple_fb_share_button_options&sub=options' ); ?>">Return to plugin options</a></h4>
	<?php else: ?>
		<h3><a href="<?php echo admin_url( 'options-general.php?page=simple_fb_share_button_options&sub=help' ); ?>">Plugin Help</a></h3>
	<?php endif;
	
		switch( $_GET[ 'sub' ] ) {
		
		default:
		case 'options':
			?>
			<form method="post" action="options.php">
				<div id="poststuff" class="metabox-holder has-right-sidebar"> 
					<div class="postbox">
						<h3>Display Settings</h3>
	
						<table class="form-table" cellspacing="2" cellpadding="5" width="100%">
							<tr>
								<th width="30%" valign="top">Display button automatically based on options below?</th>
								<td valign="top">
									<input type="radio" name="options[display]" value="1"<?php checked( $options[ 'display' ], 1, true ); ?>> Yes <br />
									<input type="radio" name="options[display]" value="0"<?php checked( $options[ 'display' ], 0, true ); ?>> No
									<p>
										<em>If set to <strong>No</strong>, the remaining options on this page are ignored. See the <a href="<?php echo admin_url( 'options-general.php?page=simple_fb_share_button_options&sub=help' ); ?>">Help page</a> for manual button display options.</em>
									</p>
								</td>
							</tr>
							<tr>
								<th width="30%" valign="top">Display on:</th>
								<td>
									<select name="options[content]">
										<option value="post"<?php selected( $options[ 'content' ], 'post', true ); ?>>Posts</option>
										<option value="page"<?php selected( $options[ 'content' ], 'page', true ); ?>>Pages</option>
										<option value="both"<?php selected( $options[ 'content' ], 'both', true ); ?>>Posts &amp; Pages</option>
									</select>
								</td>
							</tr>
							<tr>
								<th></th>
								<td>
									<input type="checkbox" name="options[content-excerpt]" value="1"<?php checked( $options[ 'content-excerpt' ], 1, true ); ?> /> Display on post excerpts too?
									<br />If the button is automatically displayed on posts, checking this option will display it for excerpts (generated by <a href="http://codex.wordpress.org/Function_Reference/the_excerpt" target="_blank"><code>the_excerpt()</code></a>) as well.
								</td>
							</tr>
						</table>
					</div>
					
					<div class="postbox">
						<h3>Button Style & Placement</h3>
						<table class="form-table" cellspacing="2" cellpadding="5" width="100%">
							<tr>
					 			<th width="30%" valign="top">Style</th>
									<td>
										<table width="100%" cellpadding="5" cellspacing="2">
											<tr>
												<td width="33%" valign="top" align="center">
													<input type="radio" name="options[button]" value="box_count"<?php checked( $options[ 'button' ], 'box_count', true ); ?> /><br />
													<img src="<?php echo $imgbase; ?>buttons/box_count.png" alt="box_count"><br />
													<small>See note below regarding button placement.</small>
												</td>
												<td width="34%" valign="top" align="center">
													<input type="radio" name="options[button]" value="button_count"<?php checked( $options[ 'button' ], 'button_count', true ); ?> /><br />
													<img src="<?php echo $imgbase; ?>buttons/button_count.png" alt="button_count">
												</td>
												<td width="33%" valign="top" align="center">
													<input type="radio" name="options[button]" value="button"<?php checked( $options[ 'button' ], 'button', true ); ?> /><br />
													<img src="<?php echo $imgbase; ?>buttons/button.png" alt="button">
												</td>
											</tr>
											<tr>
												<td width="33%" valign="top" align="center">
													<input type="radio" name="options[button]" value="icon"<?php checked( $options[ 'button' ], 'icon', true ); ?> /><br />
													<img src="<?php echo $imgbase; ?>buttons/icon.png" alt="icon">
												</td>
												<td width="34%" valign="top" align="center">
													<input type="radio" name="options[button]" value="custom"<?php checked( $options[ 'button' ], 'custom', true ); ?> /><br />
													<img src="<?php echo $imgbase; ?>buttons/icon.png" align="absmiddle" alt="custom">
													<input type="text" size="20" name="options[custom_text]" value="<?php echo $options[ 'custom_text' ]; ?>" /><br />
													<small>Use the box above to display custom text adjacent to the Facebook icon.</small>
												</td>
												<td width="33%" valign="top" align="center">
												</td>
											</tr>								
										</table>
										<p>
											<em>Note that depending on your theme, the large button featuring share counts may display in an unexpected manner due to Facebook's rendering of that button. Until Facebook resolves this issue, you may need to enable a <strong>Theme Compatibility Mode</strong> under <strong>Advanced Settings</strong> or specify padding (particularly if displaying the button below your posts) to prevent the button from overlapping other elements of your theme.</em>
										</p>
									</td>
								</tr>
								<tr>
									<th width="30%" valign="top">
										Position
										<p style="padding-left:6px;padding-right:6px;">
											<small>Default CSS style shown below each option.</small>
										</p>
									</th>
									<td>
										<table width="100%" cellpadding="5" cellspacing="2">
											<tr>
												<td width="25%" valign="top" align="center">
													<input type="radio" name="options[placement]" value="tl"<?php checked( $options[ 'placement' ], 'tl', true ); ?> /><br />Top left
												</td>
												<td width="25%" valign="top" align="center">
													<input type="radio" name="options[placement]" value="tr"<?php checked( $options[ 'placement' ], 'tr', true ); ?> /><br />Top right
												</td>
												<td width="25%" valign="top" align="center">
													<input type="radio" name="options[placement]" value="bl"<?php checked( $options[ 'placement' ], 'bl', true ); ?> /><br />Bottom left
												</td>
												<td width="25%" valign="top" align="center">
													<input type="radio" name="options[placement]" value="br"<?php checked( $options[ 'placement' ], 'br', true ); ?> /><br />Bottom right
												</td>
											</tr>
											<tr>
												<td width="25%" valign="top" align="center">
													<code>
														float:left;<br />
														padding-top: 0px;<br />
														padding-bottom: 5px;<br />
														padding-left: 0px;<br />
														padding-right: 5px;
													</code>
												</td>
												<td width="25%" valign="top" align="center">
													<code>
														float:right;<br />
														padding-top: 0px;<br />
														padding-bottom: 5px;<br />
														padding-left: 5px;<br />
														padding-right: 0px;
													</code>
												</td>
												<td width="25%" valign="top" align="center">
													<code>
														float:left;<br />
														padding-top: 5px;<br />
														padding-bottom: 0px;<br />
														padding-left: 0px;<br />
														padding-right: 5px;
													</code>
												</td>
												<td width="25%" valign="top" align="center">
													<code>
														float:right;<br />
														padding-top: 5px;<br />
														padding-bottom: 0px;<br />
														padding-left: 5px;<br />
														padding-right: 0px;
													</code>
												</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</div>
			
						<div class="postbox"><h3>Advanced Settings</h3>
							<table class="form-table" cellspacing="2" cellpadding="5" width="100%">
								<tr>
									<th width="30%" valign="top">Theme Compatibility Modes</th>
									<td colspan="2">
										<select name="options[compatibility]">
											<option value="0"<?php selected( $options[ 'compatibility' ], 0, true ); ?>>Disabled</option>
											<option value="1"<?php selected( $options[ 'compatibility' ], 1, true ); ?>>Mode 1</option>
											<option value="2"<?php selected( $options[ 'compatibility' ], 2, true ); ?>>Mode 2</option>
											<option value="3"<?php selected( $options[ 'compatibility' ], 3, true ); ?>>Mode 3</option>
										</select><br />
										<em>If the button is overlapping other elements of your theme, enable one of the compatibility modes, beginning with <strong>Mode 1</strong>. If compatibility mode does not resolve the problem, a <strong>Custom Style</strong> may be necessary.<br /><br />For more information on these modes, see the <a href="<?php echo admin_url( 'options-general.php?page=simple_fb_share_button_options&sub=help' ); ?>">Help page</a>.</em>
									</td>
								</tr>
								<tr>
									<th width="30%" valign="top">Vertical Padding</th>
									<td width="6">Top:</td>
									<td>
										<input type="text" size="3" name="options[tpad]" value="<?php echo $options[ 'tpad' ]; ?>" /> px
									</td>
								</tr>
								<tr>
									<th></th>
									<td width="6">Bottom:</td>
									<td><input type="text" size="3" name="options[bpad]" value="<?php echo $options[ 'bpad' ]; ?>" /> px</td>
								</tr>
								<tr>
									<th></th>
									<td colspan="2">
										<em>To override the default vertical padding without changing the remaining formatting, enter a new value above. By default, 5px padding is added to the side nearest your content.</em>
									</td>
								</tr>
								<tr>
									<th width="30%" valign="top">Horizontal Padding</th>
									<td width="6">Left:</td>
									<td>
										<input type="text" size="3" name="options[lpad]" value="<?php echo $options[ 'lpad' ]; ?>" /> px
									</td>
								</tr>
								<tr>
									<th></th>
									<td width="6">Right:</td>
									<td>
										<input type="text" size="3" name="options[rpad]" value="<?php echo $options[ 'rpad' ]; ?>" /> px
									</td>
								</tr>
								<tr>
									<th></th>
									<td colspan="2">
										<em>To override the default horizontal padding without changing the remaining formatting, enter a new value above. By default, 5px padding is added to the side of the button nearest your content.</em>
									</td>
								</tr>
								<tr>
									<th width="30%" valign="top">Custom CSS Style</th>
									<td colspan="2">
										<input type="text" size="40" name="options[style]" value="<?php echo $options[ 'style' ]; ?>" /><br />
										<em>To override a position's default style (shown below the selected position), enter CSS above.
									</td>
								</tr>
							</table>
						</div>
						
						<div class="postbox">
							<h3>Uninstall</h3>
							<table class="form-table" cellspacing="2" cellpadding="5" width="100%">
								<tr>
									<th width="30%" valign="top">Delete settings when plugin deactivated?</th>
									<td>
										<input type="checkbox" name="options[uninstall]" value="1"<?php checked( $options[ 'uninstall' ], 1, true ); ?> /><br />
										<em>To remove all plugin settings when the plugin is next deactivated, check the box above.</em>
									</td>
								</tr>
							</table>
						</div>
					</div>
				
				<p class="submit">
					<input type="submit" class="button-primary" value="Save Changes" />
				</p>
				
				<?php settings_fields( 'SFBSB' ); ?>
			</form>
		<?php
		break;
		
		case "help":
		?>
			<div id="poststuff" class="metabox-holder has-right-sidebar"> 
				<div class="postbox"><h3>General Questions</h3>
					<div style="margin:4px;">
						<strong>Why was the <code>SFBSB_do()</code> function removed?</strong>
							<p>The function, included in versions 0.5 and 0.6 of the plugin, was difficult to implement because it used the button type, CSS style, and alignment options provided in the plugin's options page. As a result, if a user wanted the button to automatically display on posts and selectively display on pages, any options (CSS style in particular) had to be uniform across the content. Also, because the function wrapped the button in a <code>&lt;div&gt;</code> tag automatically, a user's options for the button were fairly limited.</p><p>In light of these limitations, the <code>SFBSB_do()</code> function was replaced by <code>SFBSB_direct()</code>, a function that simply generates the button code. This option provides users with greater control over the button's placement and separates the function's options from those used to automatically place the button. More information on the new function is available below.</p>
							<br /><br />
						<strong>Can I show the button only on specific posts or pages?</strong>
							<p>If you only want to display the Facebook&reg; Share button on selected posts or pages, use the <code>[SFBSB]</code> shortcode as described in the third section of this help page.</p>
							<br /><br />
						<strong>What are the Theme Compatibility Modes?</strong>
							<p>In certain themes, the button may overlap other theme elements, such as comment buttons or other plugins. The plugin includes three compatibility modes to help resolve these problems with minimal effort user effort. Know that in some cases, these modes will not resolve button placement problems and a custom CSS style may be needed.</p>
							<p style="margin-left:10px;"><strong>Mode 1</strong> disables the CSS float property (a setting that allows the button to, as the name implies, float adjacent to your blog's content) and relies on the alignment of the button wrapper to place the button.</p>
							<p style="margin-left:10px;"><strong>Mode 2</strong> prevents other elements from floating adjacent to the button (using the CSS clear property).</p>
							<p style="margin-left:10px;"><strong>Mode 3</strong> combines the functions of Modes 1 and 2.</p>
					</div>
				</div>
				
				<div class="postbox">
					<h3>Using the function SFBSB_direct();</h3>
					<div style="margin:4px;">
						<strong>How do I add the SFBSB_direct function to my site?</strong>
							<p>To utilize the "direct implementation" function, insert the code shown below where you would like the button to display, replacing <em>x</em> with one of the options described in the next question. The code should be placed within <a href="http://codex.wordpress.org/The_Loop" target="_blank">the loop</a> and enclosed in a <code>&lt;div&gt;</code> tag to support styling and alignment.</p><p style="text-align:center;"><code>&lt;?php if(function_exists(&quot;SFBSB_direct&quot;)) {echo SFBSB_direct(&quot;<em>x</em>&quot;);} ?&gt;</code></p>
							<br /><br />
						<strong>What options does the function accept?</strong>
							<p>The <code>SFBSB_direct()</code> function has only one option, and it's not required. If the <em>x</em> shown above is omitted (along with the quotation marks surrounding it), the default button will be generated. To generate one of the other button options, replace <em>x</em> with the button type named below. To display custom text alognside the Facebook&reg; icon, replace <em>x</em> with your desired text.</p>
				
						<div align="center">
							<table style="text-align:center;" width="40%" cellpadding="2" cellspacing="2">
								<tr>
									<td valign="bottom"><?php echo '<img src="' . $imgbase . 'buttons/button.png" alt="button">'; ?></td>
									<td valign="bottom"><?php echo '<img src="' . $imgbase . 'buttons/box_count.png" alt="button">'; ?></td>
									<td valign="bottom"><?php echo '<img src="' . $imgbase . 'buttons/button_count.png" alt="button">'; ?></td>
									<td valign="bottom"><?php echo '<img src="' . $imgbase . 'buttons/icon.png" alt="button">'; ?></td>
								</tr>
								<tr>
									<td valign="top"><span style="font-size:10px;">button<br /><em>(default)</em></span></td>
									<td valign="top"><span style="font-size:10px;">box_count</span></td>
									<td valign="top"><span style="font-size:10px;">button_count</span></td>
									<td valign="top"><span style="font-size:10px;">icon</span></td>
								</tr>
							</table>
						</div>
					</div>
				</div>
	
				<div class="postbox">
					<h3>Using the shortcode [SFBSB]</h3>
					<div style="margin:4px;">
						<strong>How do I use the shortcode [SFBSB]?</strong>
							<p>The shortcode is used to selectively add the Facebook&reg; Share button to your blog's content. When composing a post or page, include [SFBSB] either before the first line or after the last line of the content, depending on whether you would like the button to appear before or after your content.</p><p>If no options are specified, the default button style is used and the button will float on the lefthand side of your content. By default, no padding or strict alignment settings are specified. For your reference, the default <code>&lt;div&gt;</code> tag is shown below.</p><p style="text-align:center;"><code>&lt;div style=&quot;float:left;&quot;&gt;</code></p>
							<br /><br />
						<strong>What options can be used with the shortcode?</strong>
							<p>The shortcode supports four options. None are required, and you can specify only those you would like to override. The shortcode's default options are discussed in the preceding question.</p><p>Options are specified in the following format: <code>[SFBSB option_name="option_value"]</code>. The available options are:</p><p style="margin-left:10px;"><strong>button</strong> - Enter any of the four button types named in the help section for the SFBSB_direct function, or enter &quot;custom&quot; to specify custom text to display beside the Facebook&reg; icon.</p><p style="margin-left:10px;"><strong>style</strong> - Enter any valid CSS code.</p><p style="margin-left:10px;"><strong>align</strong> - Enter any of the three valid alignment options, either left, center, or right.</p><p style="margin-left:10px;"><strong>custom_text</strong> - To display custom text adjacent to the Facebook&reg; icon, enter your custom text and set the button option to &quot;custom&quot;.</p><p>The following example would display the box count button to the left of your content with 4px padding on the right and bottom of the button.</p><p style="text-align:center;"><code>[SFBSB button=&quot;box_count&quot; style=&quot;float:left;padding-right:4px;padding-bottom:4px;&quot;]</code></p>
					</div>
				</div>
			</div>
			<h4><a href="<?php echo admin_url( 'options-general.php?page=simple_fb_share_button_options&sub=options' ); ?>">Return to plugin options</a></h4>
		<?php
			break;
		}
	?>
		<p>
			<em>Facebook is a registered trademark of Facebook, Inc.</em>
		</p>
	</div>
	<?php
}

/*
 * Validate options
 * @uses wp_verify_nonce, sanitize_text_field, wp_die
 * @return array
 */
function SFBSB_validation() {
	if( wp_verify_nonce( $_POST[ '_wpnonce' ], 'SFBSB-options' ) ) {
		$options = array();
		
		foreach( $_POST[ 'options' ] as $option => $value ) {
			$value = sanitize_text_field( $value );
			if( strlen( $value ) > 0 ) $options[ $option ] = $value;
		}
	
		return $options;
	}
	else wp_die( 'Something has gone awry...' );
}
?>